apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lencrypt
  name: lencrypt
spec:
  replicas: 10
  selector:
    matchLabels:
      app: lencrypt
  strategy: {}
  template:
    metadata:
      labels:
        app: lencrypt
    spec:
      containers:
        - env:
            - name: CHACHA20_KEY
              value: "12345678901234567890123456789012"
          image: jamilakassem/socks-chaining_encrypt-cli
          command: ["./functions"]
          args: ["chacha20", "--key", "12345678901234567890123456789012"]
          name: lencrypt
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: lencrypt
spec:
  type: ClusterIP
  selector:
    app: lencrypt
  ports:
    - port: 1080
#      targetPort: 1080
#      nodePort: 30011
      protocol: TCP
